services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dstasks-api-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 7d
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - dstasks-network-dev
    command: npm run dev

networks:
  dstasks-network-dev:
    driver: bridge
