services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dstasks-api-dev
    restart: unless-stopped
    env_file:
      - ./api/env/.env.development
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    networks:
      - dstasks-network-dev
    command: npm run dev

networks:
  dstasks-network-dev:
    driver: bridge
