services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dstasks
    restart: unless-stopped
    env_file:
      - ./api/env/.env.production
    ports:
      - "3000:3000"
    networks:
      - dstasks-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: dstasks-app
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - dstasks-network

networks:
  dstasks-network:
    driver: bridge
